### ISSUE TITLE
암장 전체 조회

### ISSUE THREAD

**Issue by als95** [Co-Laon/claon-server#119]
## Describe
새로운 세팅 암장
즐겨찾는 암장
내 주변 암장
새로운 암장

암장 조회 화면에서 사용될 API를 개발합니다. 
<img width="348" alt="image" src="https://user-images.githubusercontent.com/20383992/183280190-f5390c46-5d47-4aef-bfd6-34eec1afb2b7.png">

**Comment by hoonkii** [comment]
@als95 @ChanghyukWoo  새로운 세팅은 무엇을 의미하는 건가요? 
새로운 암장은 "일주일 내" 새로 등록된 암장 정보를 보여주면 될까요?

**Comment by ChanghyukWoo** [comment]
@hoonkii 새로운 세팅은 암장이 섹터가 나눠져있고 이 섹터의 문제들을 일정 기간마다 비꿉니다 예컨대, 암장에 구간별로 a b c d 섹터가 있고 a섹터는 월 첫 주에 바꾸고 b는 둘째 주 c는 셋째 d는 넷째 이렇게 바꿔서 각 섹터 문제를 보통 한 달 유지하는 경우가 많아요 때문에 클라이머들이 주로 세팅이 바뀌는 시기에 관심이 많아서 저런 기획을 냈습니닷

**Comment by hoonkii** [comment]
오 그런게 있군요 ! 좋네요 👍  
다만 클라이밍 center 사장님이 플랫폼에 들어와서 세팅 정보를 바꿔야 알 수 있겠군요 ㅠ

**Comment by als95** [comment]
네 ㅠㅠ 그래서 저희가 매번 데이터를 넣어주어야합니다... ㅠㅠ 디비에는 sector_info 라는 column에 있습니다!
만약 따로 테이블을 나눠야 한다면 나누셔도 됩니다!
