### ISSUE TITLE
개인페이지 암장 및 홀드 정보를 이용한 게시글 필터링

### ISSUE THREAD

**Issue by als95** [Co-Laon/claon-server#257]
## Describe
![image](https://user-images.githubusercontent.com/37828653/193509269-4efb974a-8a09-4543-817c-738f1b0efcb1.png)
암장 이름 및 등반 기록(홀드) 클릭 시 게시글 필터링

## (Optional) Solution
Please describe your preferred solution

-

**Comment by hoonkii** [comment]
오 이슈 description에 기획안이 보이니 너무 좋네요 👍
