### ISSUE TITLE
S3 객체(이미지) 삭제 구현

### ISSUE THREAD

**Issue by als95** [Co-Laon/claon-server#259]
## Describe
Please describe the problem to be solved

## (Optional) Solution
Please describe your preferred solution

-

**Comment by hoonkii** [comment]
이미지 삭제는 API로 제공되나요? 어떤 경우에 사용되는지 궁금합니다 !

**Comment by als95** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/37828653/194756309-67e32717-0ac7-4ef7-acb2-4a54a32f2932.png">
여기서 게시글 수정시 이미지를 바꾸거나 삭제할 때 api를 사용할 것 같습니다.
