### ISSUE TITLE
Endpoint URL 리팩토링

### ISSUE THREAD

**Issue by als95** [Co-Laon/claon-server#264]
## Describe
수정 혹은 논의 필요
- /posts?centerId=&holdId=
- home controller
- storage controller
- writer controller
- /users/blocked-users
- /users/me
- /users/public-scope

## (Optional) Solution
Please describe your preferred solution

-

**Comment by hoonkii** [comment]
위 API Path가 자연스럽지 않아서 수정해야 한다는 것일까요?
