### ISSUE TITLE
이용자가 게시한 특정 월, 특정 암장에 대한 게시글 상세 조회

### ISSUE THREAD

**Issue by als95** [Co-Laon/claon-server#317]
## Describe
<img width="386" alt="image" src="https://user-images.githubusercontent.com/37828653/201843838-d3078e4a-cb62-4b8e-bedf-c9bc67e657ac.png">

## (Optional) Solution
Please describe your preferred solution

-

**Comment by siniphia** [comment]
제가 처리해보겠습니다
